jo = "0.12"

[module.api]
kind = "lib"
platform = "python"
src = ["SandboxAPI.jo"]

[module.runtime]
kind = "lib"
platform = "python"
src = ["SandboxRuntime.jo"]
modules = ["api"]

[module.guest]
kind = "app"
platform = "python"
src = ["Task.jo"]
modules = ["api", { id = "runtime", link = true }]

links = [
  { from = "jo.main", to = "sandbox.runtime.main" },
  { from = "sandbox.api.runTask", to = "sandbox.guest.runTask" },
]
