jo   = "0.11"
name = "pr-review"

[main]
target = "python"
compile-options = ["--use-runtime-api", "python"]

[main.dependencies]
harpe = { path = "../../agent" }

[main.links]
"jo.main" = "harpe.examples.prreview.main"

[commands]
start = "jo build --spec sandbox/guest/jo.toml && jo run"
