jo   = "0.11"
name = "sandbox-guest"

[main]
target = "python"
src    = ["src/"]

[main.dependencies]
sandbox-api     = { path = "../api" }
sandbox-runtime = { path = "../runtime", link = true }

[main.links]
"jo.main"          = "SandboxRuntime.main"
"SandboxAPI.runTask" = "UserTask.runTask"
