jo = "0.12"

[module.telegram]
kind = "app"
platform = "python"
enable-ffi = true
src = ["../telegram/src/"]
modules = [{ id = "harpe", path = ".." }]

links = [
  { from = "jo.main", to = "harpe.telegram.main" },
]

[module.sandbox-api]
kind = "lib"
platform = "python"
src = ["../telegram/sandbox/SandboxAPI.jo"]
modules = [{ id = "caps", path = ".." }]

[module.sandbox-runtime]
kind = "lib"
platform = "python"
enable-ffi = true
src = ["../telegram/sandbox/SandboxRuntime.jo"]
modules = ["sandbox-api", { id = "harpe", path = ".." }]

[module.sandbox-guest]
kind = "app"
platform = "python"
src = ["../telegram/sandbox/Task.jo"]
modules = [
  "sandbox-api",
  { id = "caps", path = ".." },
  { id = "sandbox-runtime", link = true },
]

links = [
  { from = "jo.main", to = "sandbox.runtime.main" },
  { from = "sandbox.api.runTask", to = "sandbox.guest.runTask" },
]
