jo = "0.12"

[module.harpe]
kind = "lib"
platform = "python"
src = ["src/"]
compile-options = ["--test-pickling", "--check-tree"]
enable-ffi = true

[module.harpe.package]
name = "harpe"
version = "0.1.0"

[module.test]
kind = "app"
platform = "python"
enable-ffi = true
modules = ["harpe"]
src = ["tests/"]
