jo = "0.12"

[module.agent]
kind = "app"
platform = "python"
enable-ffi = true
src = ["src/"]
depth = 2

packages = [{ name = "harpe", version = "0.6" }]

links = [
  { from = "jo.main", to = "harpe.examples.flightbooker.main" },
]

[commands]
start = "jo build --spec sandbox/jo.toml guest && jo run"
