jo = "0.12"

[module.agent]
kind = "app"
platform = "python"
enable-ffi = true
src = ["src/"]

modules = [{ id = "harpe", path = "../.." }]

links = [
  { from = "jo.main", to = "hello.main" },
]

[commands]
start = "jo build --spec sandbox/jo.toml guest && jo run"
